services:
  - docker

cache:
  directories:
    - docker_images

before_install:
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

env:
  - FOO=0
  - FOO=1

script: docker run --rm test/example bash -c "echo $FOO & ls"