language:
  - javascript

services:
  - docker

stages:
  - setup
  - test

cache:
  directories:
    - docker_images

before_install:
  - docker load -i docker_images/images.tar || true
  - docker build -t test/example .

env:
  - FOO=0
  - FOO=1

script: docker run --rm test/example bash -c "echo $FOO & ls"

jobs:
  include:
    - name: build docker image
      stage: setup
      script: docker save -o docker_images/images.tar $(docker images -a -q)