services:
  - docker

jobs:
  include:
    - name: docker
      script: docker build -t test/example .
    - name: test
      script: docker run --rm test/example bash -c "echo $FOO & ls"
      env:
        - FOO=0
        - FOO=1